### ISSUE TITLE
Verify all data on Perlmutter is uncompressed

### ISSUE THREAD

**Issue by IamShubhamGupto** [m2lines/Samudra#16]
Nvidia's recommendation is to not load compressed zarr to gpu, need to verify the data we're working with is indeed uncompressed zarrs. will be making a script like https://github.com/m2lines/ocean_emulators/issues/59#issuecomment-2289742953 and see if automations are available

**Comment by suryadheeshjith** [comment]
Referencing comment [here](https://github.com/m2lines/ocean_emulators/issues/59#issuecomment-2289847149).
